blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include("posts.urls", namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url

from .views import (post_list, post_create, post_delete, post_detail, post_update)

urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
]

comments/models.py
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from posts.models import Post


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    #post = models.ForeignKey(Post)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user.username)

posts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.safestring import mark_safe
from markdown_deux import markdown


# Overwriting the all
class PostManager(models.Manager):
    def active(self, *arg, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s" %(instance.id, instance.id, extension)
    return "%s/%s" % (instance.slug, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
            null=True,
            blank=True,
            height_field="height_field",
            width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    publish = models.DateTimeField(auto_now=False, auto_now_add=False)
    draft = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "updated"]

    def get_markdown(self):
        content = self.content
        return mark_safe(markdown(content))

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    querySet = Post.objects.filter(slug=slug).order_by("-id")
    exists = querySet.exists()
    if exists:
        new_slug = "%s-%s" %(slug, querySet.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *arg, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

comments/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from urllib.parse import quote_plus

from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from comments.models import Comment
from posts.models import Post
from .forms import PostForm


def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "title": "New Post",
        "form": form
    }
    return render(request, "post_form.html", context)


def post_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    if instance.publish > timezone.now() or instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)
    content_type = ContentType.objects.get_for_model(Post)
    obj_id = instance.id
    comments = Comment.objects.filter(content_type=content_type, object_id=obj_id)

    context = {
        "title": instance.title,
        "instance": instance,
        "share_string": share_string,
        "comments": comments
    }
    return render(request, "post_detail.html", context)


def post_list(request):
    today = timezone.now().date()
    queryset_list = Post.objects.active()#.filter(draft=False).filter(publish__lte=timezone.now())
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()
    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query)|
            Q(content__icontains=query)|
            Q(user__first_name__icontains=query)|
            Q(user__last_name__icontains=query)
        ).distinct()
    paginator = Paginator(queryset_list, 3)  # Show 3 posts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        "title": "List View",
        "object_list": queryset,
        "page_request_var": page_request_var,
        "today": today
    }
    return render(request, "post_list.html", context)


def post_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Successfully Edited")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "title": "Update",
        "instance": instance,
        "form": form,
    }
    return render(request, "post_form.html", context)


def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Successfully Deleted")
    return redirect("posts:list")

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}Blog - {{title}}{% endblock head_title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href='{% static "css/base.css" %}'>
    {% block head_extra %}
    {% endblock head_extra %}
</head>
<body>
    {% include "messages_display.html" %}
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(".post-detail-item img").each(function () {
                $(this).addClass("img-responsive");
            });

            function setContent(value) {
              $("#preview-content").html(marked(value));
              $("#preview-content img").each(function () {
                  $(this).addClass("img-responsive");
              })
            }
            function setTitle(value) {
                $("#preview-title").text(value);
            }

            var titleInput = $("#id_title"),
                contentInput = $("#id_content");

            contentInput.keyup(function () {
               setContent(contentInput.val());
            });
            titleInput.keyup(function () {
                setTitle(titleInput.val());
            });

            setContent(contentInput.val());
            setTitle(titleInput.val());



        });
    </script>
</body>
</html>

templates/messages_display.html
{% if messages %}
<div class="message">
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="col-sm-6 col-sm-offset-3">
    {% if instance.image %}
    <img src="{{ instance.image.url }}" class="img-responsive"/>
    {% endif %}
    <h1>{{ title }} <small>{% if instance.draft %}<span style='color:red;'>Draft</span>{% endif %} {{ instance.timestamp }}</small></h1>
    <p>Author: {{ instance.user }}</p>

    <p>
        <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
        <hr/>
    </p>

    <!--<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
        Share on Facebook
    </a>
    <a href="https://twitter.com/home?status={{ instance.content|truncatechars:80|urlify }}%20{{ request.build_absolute_uri }}">
        Share on Twitter
    </a>
    <a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>
    <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}">
        Share on Linkedin
    </a>-->

     <div class='row'>
        <div class='col-sm-12 '>
            <div class="post-detail-item">{{ instance.get_markdown }}</div>
            <hr/>
            <br/>
            <div>
                <p class="lead">Comments</p>
                {% for comment in comments %}
                    {{ comment.content_object }}
                    <div class="">
                        {{ comment.content }}<br>
                        by {{ comment.user }}, {{ comment.timestamp|timesince }} ago.<hr>
                    </div>
                {% endfor %}
                <!--{{ instance.comment_set.all }}-->
            </div>
            <!--<div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>-->
        </div>
     </div>

</div>

{% endblock content %}

templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %}
    {{ form.media }}
{% endblock head_extra %}

{% block content %}

<div class="col-sm-6">
    <h1>Preview</h1>
    <hr>
    <div class="content-preview">
        <h3 id="preview-title"></h3>
        <p id="preview-content"></p>
    </div>
</div>
<div class="col-sm-6">
    <h1>Form</h1>
    <hr>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-default" value="Create Post" />
    </form>
</div>

{% endblock content %}

templates/post_list.html
{% extends "base.html" %}
{% block content %}

<div class="col-sm-6 col-sm-offset-3">
    <h1>{{ title }}</h1>
    <form method="GET" action="">
        <div class="input-group">
            <input class="form-control" type="text" name="q" placeholder="Search posts" value="{{ request.GET.q }}"/>
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
            </span>
        </div>
    </form>
    <br>
    <div class="row">
        {% for object in object_list %}
        <div class="col-sm-12">
            <div class="thumbnail">
                {% if object.image %}
                <img src="{{ object.image.url }}" class="img-responsive"/>
                {% endif %}
                <div class="caption post-detail-item">
                    {% if object.draft %}
                    <h3>Draft {% if object.publish > today %}Future Post{% endif %}</h3>
                    {% endif %}
                    <h3>
                        <a href='{{ object.get_absolute_url }}'>{{ object.title }}</a>
                        <small>{{ object.timestamp | timesince }} ago</small>
                    </h3>
                    <p>Author: {{ object.user }}</p>
                    {{ object.get_markdown | truncatechars_html:120 }}
                    <p>
                        <a href="{{ object.get_absolute_url }}" class="btn btn-primary" role="button">View</a>
                    </p>
                </div>
            </div>
        </div>
        {% cycle "" "</div><div class='row'>" %}
        {% endfor %}
    </div>
</div>

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>

{% endblock content %}